### ISSUE TITLE
Plgx references a specific version of KeePass (2.36)

### ISSUE THREAD

**Issue by kazyka** [andrew-schofield/keepass2-haveibeenpwned#9]
As the title state, I get a pop up that tells me it is incompatible with the current version of keepass

**Comment by andrew-schofield** [comment]
Duplicate of #1 Won't actually work with any version except a development build at present

**Comment by boistordu** [comment]
still nothing about that ? we can't run it on the normal version of keepass? Would be a good idea to put it like in BIG RED on the readme no ? It is still not workin on 2.37 nor 2.34 on fedora 25 with mono-devel 4.4

**Comment by Sanaki** [comment]
For what it's worth, it works perfectly fine on windows keepass, even on 2.37.

**Comment by andrew-schofield** [comment]
Are those of you who are having a problem using the plgx package or the DLLs?

* If you're using the DLLs have you got all 3 installed?

* If you're using the plgx have you got `mono-complete` or your distro's equivalent installed? If that still doesn't work, can you pass the `--debug` option to KeePass as described here: https://keepass.info/help/v2_dev/plg_index.html and report what the errors are.

**Comment by andrew-schofield** [comment]
Incidentally, my first comment in this issue about requiring a development version of KeePass hasn't been true for months. The plugin is built against the release builds of KeePass.

**Comment by boistordu** [comment]
didn't try it on windows. 
I have the three dlls in the folder yes.
ow okey so it should work then.... I'm going to check about the mono-complete but in fedora i'm not sure that it is not in the mono-devel itself.

**Comment by boistordu** [comment]
okey it seems to have worked and I don't know why. Did I forget before a dll or it was a misinteraction with another mod that I've deleteddisturbance.  afterwards. Anyway it works even on fedora. 
Thanks and sorry for the

**Comment by boistordu** [comment]
I didn't try with 2.34 which is in the fedora repo by default. I will.

**Comment by boistordu** [comment]
okey not working in 2.4 but i guess it s normal. 
Just to be sure you know : 
```
[user@vault tmp]$ more tmp6617f443.tmp 
==============================================================================
Compiler 'null':

/usr/bin/mcs /target:library /debug- /optimize+ /out:"/run/user/1000/KeePass/FE2
1AEB3E87F2743B60418E1A02B1B13/HaveIBeenPwned.dll" /r:"System.dll" /r:"System.Cor
e.dll" /r:"System.Drawing.dll" /r:"System.Windows.Forms.dll" /r:"System.Xml.Linq
.dll" /r:"System.Data.DataSetExtensions.dll" /r:"Microsoft.CSharp.dll" /r:"Syste
m.Data.dll" /r:"System.Net.Http.dll" /r:"System.Xml.dll" /r:"/usr/lib/keepass/Ke
ePass.exe" /r:"/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/
Newtonsoft.Json.dll" /r:"/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH
7zcIs5G7h/keepass2-developerextensions.dll" /resource:"/run/user/1000/KeePass/FE
21AEB3E87F2743B60418E1A02B1B13/HaveIBeenPwned.UI.BreachedEntriesDialog.resources
" /resource:"/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/HaveIBeenPw
ned.UI.CheckerPrompt.resources" /resource:"/run/user/1000/KeePass/FE21AEB3E87F27
43B60418E1A02B1B13/HaveIBeenPwned.Resources.resources"  -- "/run/user/1000/KeePa
ss/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/BaseChecker.cs" "/run/user/10
00/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedPasswor
d/HaveIBeenPwnedPasswordChecker.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B604
18E1A02B1B13/BreachCheckers/HaveIBeenPwnedPassword/HaveIBeenPwnedPasswordEntry.c
s" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveI
BeenPwnedUsername/HaveIBeenPwnedUsernameChecker.cs" "/run/user/1000/KeePass/FE21
AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedUsername/HaveIBeenPwne
dUsernameEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/Disp
layAttribute.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/UI/Bre
achedEntriesDialog.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/
UI/BreachedEntriesDialog.Designer.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B6
0418E1A02B1B13/BreachCheckers/BreachedEntry.cs" "/run/user/1000/KeePass/FE21AEB3
E87F2743B60418E1A02B1B13/BreachEnum.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743
B60418E1A02B1B13/UI/CheckerPrompt.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B6
0418E1A02B1B13/UI/CheckerPrompt.Designer.cs" "/run/user/1000/KeePass/FE21AEB3E87
F2743B60418E1A02B1B13/BreachCheckers/CloudbleedSite/CloudbleedSiteChecker.cs" "/
run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudbleed
Site/CloudbleedSiteEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02
B1B13/CheckerTypeAttribute.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A
02B1B13/BreachCheckers/HaveIBeenPwnedSite/HaveIBeenPwnedSiteChecker.cs" "/run/us
er/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedSi
te/HaveIBeenPwnedSiteEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A
02B1B13/CheckTypeEnum.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B
13/HaveIBeenPwnedExt.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B1
3/BreachCheckers/IBreach.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02
B1B13/ProgressHelper.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B1
3/ProgressItem.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/Prop
erties/AssemblyInfo.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13
/Resources.Designer.cs"
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedPassword/HaveIBeenPwnedPasswordChecker.cs(37,103): error CS0012: The type `
KeePassLib.PwEntry' is defined in an assembly that is not referenced. Consider a
dding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, P
ublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedPassword/HaveIBeenPwnedPasswordChecker.cs(37,103): error CS0012: The type `
KeePass.Plugins.IPluginHost' is defined in an assembly that is not referenced. C
onsider adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=n
eutral, PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedUsername/HaveIBeenPwnedUsernameChecker.cs(36,103): error CS0012: The type `
KeePassLib.PwEntry' is defined in an assembly that is not referenced. Consider a
dding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, P
ublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedUsername/HaveIBeenPwnedUsernameChecker.cs(36,103): error CS0012: The type `
KeePass.Plugins.IPluginHost' is defined in an assembly that is not referenced. C
onsider adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=n
eutral, PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudblee
dSite/CloudbleedSiteChecker.cs(35,103): error CS0012: The type `KeePassLib.PwEnt
ry' is defined in an assembly that is not referenced. Consider adding a referenc
e to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKeyToken=fe
d2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudblee
dSite/CloudbleedSiteChecker.cs(35,103): error CS0012: The type `KeePass.Plugins.
IPluginHost' is defined in an assembly that is not referenced. Consider adding a
 reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKe
yToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedSite/HaveIBeenPwnedSiteChecker.cs(36,103): error CS0012: The type `KeePassL
ib.PwEntry' is defined in an assembly that is not referenced. Consider adding a 
reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKey
Token=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedSite/HaveIBeenPwnedSiteChecker.cs(36,103): error CS0012: The type `KeePass.
Plugins.IPluginHost' is defined in an assembly that is not referenced. Consider 
adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, 
PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)



==============================================================================
Compiler 'v4':

/usr/bin/mcs /target:library /debug- /optimize+ /out:"/run/user/1000/KeePass/FE2
1AEB3E87F2743B60418E1A02B1B13/HaveIBeenPwned.dll" /r:"System.dll" /r:"System.Cor
e.dll" /r:"System.Drawing.dll" /r:"System.Windows.Forms.dll" /r:"System.Xml.Linq
.dll" /r:"System.Data.DataSetExtensions.dll" /r:"Microsoft.CSharp.dll" /r:"Syste
m.Data.dll" /r:"System.Net.Http.dll" /r:"System.Xml.dll" /r:"/usr/lib/keepass/Ke
ePass.exe" /r:"/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/
Newtonsoft.Json.dll" /r:"/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH
7zcIs5G7h/keepass2-developerextensions.dll" /resource:"/run/user/1000/KeePass/FE
21AEB3E87F2743B60418E1A02B1B13/HaveIBeenPwned.UI.BreachedEntriesDialog.resources
" /resource:"/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/HaveIBeenPw
ned.UI.CheckerPrompt.resources" /resource:"/run/user/1000/KeePass/FE21AEB3E87F27
43B60418E1A02B1B13/HaveIBeenPwned.Resources.resources"  -- "/run/user/1000/KeePa
ss/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/BaseChecker.cs" "/run/user/10
00/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedPasswor
d/HaveIBeenPwnedPasswordChecker.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B604
18E1A02B1B13/BreachCheckers/HaveIBeenPwnedPassword/HaveIBeenPwnedPasswordEntry.c
s" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveI
BeenPwnedUsername/HaveIBeenPwnedUsernameChecker.cs" "/run/user/1000/KeePass/FE21
AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedUsername/HaveIBeenPwne
dUsernameEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/Disp
layAttribute.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/UI/Bre
achedEntriesDialog.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/
UI/BreachedEntriesDialog.Designer.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B6
0418E1A02B1B13/BreachCheckers/BreachedEntry.cs" "/run/user/1000/KeePass/FE21AEB3
E87F2743B60418E1A02B1B13/BreachEnum.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743
B60418E1A02B1B13/UI/CheckerPrompt.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B6
0418E1A02B1B13/UI/CheckerPrompt.Designer.cs" "/run/user/1000/KeePass/FE21AEB3E87
F2743B60418E1A02B1B13/BreachCheckers/CloudbleedSite/CloudbleedSiteChecker.cs" "/
run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudbleed
Site/CloudbleedSiteEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02
B1B13/CheckerTypeAttribute.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A
02B1B13/BreachCheckers/HaveIBeenPwnedSite/HaveIBeenPwnedSiteChecker.cs" "/run/us
er/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedSi
te/HaveIBeenPwnedSiteEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A
02B1B13/CheckTypeEnum.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B
13/HaveIBeenPwnedExt.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B1
3/BreachCheckers/IBreach.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02
B1B13/ProgressHelper.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B1
3/ProgressItem.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/Prop
erties/AssemblyInfo.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13
/Resources.Designer.cs"
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedPassword/HaveIBeenPwnedPasswordChecker.cs(37,103): error CS0012: The type `
KeePassLib.PwEntry' is defined in an assembly that is not referenced. Consider a
dding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, P
ublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedPassword/HaveIBeenPwnedPasswordChecker.cs(37,103): error CS0012: The type `
KeePass.Plugins.IPluginHost' is defined in an assembly that is not referenced. C
onsider adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=n
eutral, PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedUsername/HaveIBeenPwnedUsernameChecker.cs(36,103): error CS0012: The type `
KeePassLib.PwEntry' is defined in an assembly that is not referenced. Consider a
dding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, P
ublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedUsername/HaveIBeenPwnedUsernameChecker.cs(36,103): error CS0012: The type `
KeePass.Plugins.IPluginHost' is defined in an assembly that is not referenced. C
onsider adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=n
eutral, PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudblee
dSite/CloudbleedSiteChecker.cs(35,103): error CS0012: The type `KeePassLib.PwEnt
ry' is defined in an assembly that is not referenced. Consider adding a referenc
e to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKeyToken=fe
d2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudblee
dSite/CloudbleedSiteChecker.cs(35,103): error CS0012: The type `KeePass.Plugins.
IPluginHost' is defined in an assembly that is not referenced. Consider adding a
 reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKe
yToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedSite/HaveIBeenPwnedSiteChecker.cs(36,103): error CS0012: The type `KeePassL
ib.PwEntry' is defined in an assembly that is not referenced. Consider adding a 
reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKey
Token=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedSite/HaveIBeenPwnedSiteChecker.cs(36,103): error CS0012: The type `KeePass.
Plugins.IPluginHost' is defined in an assembly that is not referenced. Consider 
adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, 
PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)



==============================================================================
Compiler 'v4.0':

/usr/bin/mcs /target:library /debug- /optimize+ /out:"/run/user/1000/KeePass/FE2
1AEB3E87F2743B60418E1A02B1B13/HaveIBeenPwned.dll" /r:"System.dll" /r:"System.Cor
e.dll" /r:"System.Drawing.dll" /r:"System.Windows.Forms.dll" /r:"System.Xml.Linq
.dll" /r:"System.Data.DataSetExtensions.dll" /r:"Microsoft.CSharp.dll" /r:"Syste
m.Data.dll" /r:"System.Net.Http.dll" /r:"System.Xml.dll" /r:"/usr/lib/keepass/Ke
ePass.exe" /r:"/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/
Newtonsoft.Json.dll" /r:"/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH
7zcIs5G7h/keepass2-developerextensions.dll" /resource:"/run/user/1000/KeePass/FE
21AEB3E87F2743B60418E1A02B1B13/HaveIBeenPwned.UI.BreachedEntriesDialog.resources
" /resource:"/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/HaveIBeenPw
ned.UI.CheckerPrompt.resources" /resource:"/run/user/1000/KeePass/FE21AEB3E87F27
43B60418E1A02B1B13/HaveIBeenPwned.Resources.resources"  -- "/run/user/1000/KeePa
ss/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/BaseChecker.cs" "/run/user/10
00/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedPasswor
d/HaveIBeenPwnedPasswordChecker.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B604
18E1A02B1B13/BreachCheckers/HaveIBeenPwnedPassword/HaveIBeenPwnedPasswordEntry.c
s" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveI
BeenPwnedUsername/HaveIBeenPwnedUsernameChecker.cs" "/run/user/1000/KeePass/FE21
AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedUsername/HaveIBeenPwne
dUsernameEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/Disp
layAttribute.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/UI/Bre
achedEntriesDialog.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/
UI/BreachedEntriesDialog.Designer.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B6
0418E1A02B1B13/BreachCheckers/BreachedEntry.cs" "/run/user/1000/KeePass/FE21AEB3
E87F2743B60418E1A02B1B13/BreachEnum.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743
B60418E1A02B1B13/UI/CheckerPrompt.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B6
0418E1A02B1B13/UI/CheckerPrompt.Designer.cs" "/run/user/1000/KeePass/FE21AEB3E87
F2743B60418E1A02B1B13/BreachCheckers/CloudbleedSite/CloudbleedSiteChecker.cs" "/
run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudbleed
Site/CloudbleedSiteEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02
B1B13/CheckerTypeAttribute.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A
02B1B13/BreachCheckers/HaveIBeenPwnedSite/HaveIBeenPwnedSiteChecker.cs" "/run/us
er/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedSi
te/HaveIBeenPwnedSiteEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A
02B1B13/CheckTypeEnum.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B
13/HaveIBeenPwnedExt.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B1
3/BreachCheckers/IBreach.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02
B1B13/ProgressHelper.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B1
3/ProgressItem.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/Prop
erties/AssemblyInfo.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13
/Resources.Designer.cs"
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedPassword/HaveIBeenPwnedPasswordChecker.cs(37,103): error CS0012: The type `
KeePassLib.PwEntry' is defined in an assembly that is not referenced. Consider a
dding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, P
ublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedPassword/HaveIBeenPwnedPasswordChecker.cs(37,103): error CS0012: The type `
KeePass.Plugins.IPluginHost' is defined in an assembly that is not referenced. C
onsider adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=n
eutral, PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedUsername/HaveIBeenPwnedUsernameChecker.cs(36,103): error CS0012: The type `
KeePassLib.PwEntry' is defined in an assembly that is not referenced. Consider a
dding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, P
ublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedUsername/HaveIBeenPwnedUsernameChecker.cs(36,103): error CS0012: The type `
KeePass.Plugins.IPluginHost' is defined in an assembly that is not referenced. C
onsider adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=n
eutral, PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudblee
dSite/CloudbleedSiteChecker.cs(35,103): error CS0012: The type `KeePassLib.PwEnt
ry' is defined in an assembly that is not referenced. Consider adding a referenc
e to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKeyToken=fe
d2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudblee
dSite/CloudbleedSiteChecker.cs(35,103): error CS0012: The type `KeePass.Plugins.
IPluginHost' is defined in an assembly that is not referenced. Consider adding a
 reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKe
yToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedSite/HaveIBeenPwnedSiteChecker.cs(36,103): error CS0012: The type `KeePassL
ib.PwEntry' is defined in an assembly that is not referenced. Consider adding a 
reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKey
Token=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedSite/HaveIBeenPwnedSiteChecker.cs(36,103): error CS0012: The type `KeePass.
Plugins.IPluginHost' is defined in an assembly that is not referenced. Consider 
adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, 
PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)



==============================================================================
Compiler 'v4.0.30319':

/usr/bin/mcs /target:library /debug- /optimize+ /out:"/run/user/1000/KeePass/FE2
1AEB3E87F2743B60418E1A02B1B13/HaveIBeenPwned.dll" /r:"System.dll" /r:"System.Cor
e.dll" /r:"System.Drawing.dll" /r:"System.Windows.Forms.dll" /r:"System.Xml.Linq
.dll" /r:"System.Data.DataSetExtensions.dll" /r:"Microsoft.CSharp.dll" /r:"Syste
m.Data.dll" /r:"System.Net.Http.dll" /r:"System.Xml.dll" /r:"/usr/lib/keepass/Ke
ePass.exe" /r:"/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/
Newtonsoft.Json.dll" /r:"/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH
7zcIs5G7h/keepass2-developerextensions.dll" /resource:"/run/user/1000/KeePass/FE
21AEB3E87F2743B60418E1A02B1B13/HaveIBeenPwned.UI.BreachedEntriesDialog.resources
" /resource:"/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/HaveIBeenPw
ned.UI.CheckerPrompt.resources" /resource:"/run/user/1000/KeePass/FE21AEB3E87F27
43B60418E1A02B1B13/HaveIBeenPwned.Resources.resources"  -- "/run/user/1000/KeePa
ss/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/BaseChecker.cs" "/run/user/10
00/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedPasswor
d/HaveIBeenPwnedPasswordChecker.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B604
18E1A02B1B13/BreachCheckers/HaveIBeenPwnedPassword/HaveIBeenPwnedPasswordEntry.c
s" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveI
BeenPwnedUsername/HaveIBeenPwnedUsernameChecker.cs" "/run/user/1000/KeePass/FE21
AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedUsername/HaveIBeenPwne
dUsernameEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/Disp
layAttribute.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/UI/Bre
achedEntriesDialog.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/
UI/BreachedEntriesDialog.Designer.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B6
0418E1A02B1B13/BreachCheckers/BreachedEntry.cs" "/run/user/1000/KeePass/FE21AEB3
E87F2743B60418E1A02B1B13/BreachEnum.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743
B60418E1A02B1B13/UI/CheckerPrompt.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B6
0418E1A02B1B13/UI/CheckerPrompt.Designer.cs" "/run/user/1000/KeePass/FE21AEB3E87
F2743B60418E1A02B1B13/BreachCheckers/CloudbleedSite/CloudbleedSiteChecker.cs" "/
run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudbleed
Site/CloudbleedSiteEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02
B1B13/CheckerTypeAttribute.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A
02B1B13/BreachCheckers/HaveIBeenPwnedSite/HaveIBeenPwnedSiteChecker.cs" "/run/us
er/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedSi
te/HaveIBeenPwnedSiteEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A
02B1B13/CheckTypeEnum.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B
13/HaveIBeenPwnedExt.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B1
3/BreachCheckers/IBreach.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02
B1B13/ProgressHelper.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B1
3/ProgressItem.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/Prop
erties/AssemblyInfo.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13
/Resources.Designer.cs"
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedPassword/HaveIBeenPwnedPasswordChecker.cs(37,103): error CS0012: The type `
KeePassLib.PwEntry' is defined in an assembly that is not referenced. Consider a
dding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, P
ublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedPassword/HaveIBeenPwnedPasswordChecker.cs(37,103): error CS0012: The type `
KeePass.Plugins.IPluginHost' is defined in an assembly that is not referenced. C
onsider adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=n
eutral, PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedUsername/HaveIBeenPwnedUsernameChecker.cs(36,103): error CS0012: The type `
KeePassLib.PwEntry' is defined in an assembly that is not referenced. Consider a
dding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, P
ublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedUsername/HaveIBeenPwnedUsernameChecker.cs(36,103): error CS0012: The type `
KeePass.Plugins.IPluginHost' is defined in an assembly that is not referenced. C
onsider adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=n
eutral, PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudblee
dSite/CloudbleedSiteChecker.cs(35,103): error CS0012: The type `KeePassLib.PwEnt
ry' is defined in an assembly that is not referenced. Consider adding a referenc
e to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKeyToken=fe
d2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudblee
dSite/CloudbleedSiteChecker.cs(35,103): error CS0012: The type `KeePass.Plugins.
IPluginHost' is defined in an assembly that is not referenced. Consider adding a
 reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKe
yToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedSite/HaveIBeenPwnedSiteChecker.cs(36,103): error CS0012: The type `KeePassL
ib.PwEntry' is defined in an assembly that is not referenced. Consider adding a 
reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKey
Token=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedSite/HaveIBeenPwnedSiteChecker.cs(36,103): error CS0012: The type `KeePass.
Plugins.IPluginHost' is defined in an assembly that is not referenced. Consider 
adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, 
PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)



==============================================================================
Compiler 'v4.5':

/usr/bin/mcs /target:library /debug- /optimize+ /out:"/run/user/1000/KeePass/FE2
1AEB3E87F2743B60418E1A02B1B13/HaveIBeenPwned.dll" /r:"System.dll" /r:"System.Cor
e.dll" /r:"System.Drawing.dll" /r:"System.Windows.Forms.dll" /r:"System.Xml.Linq
.dll" /r:"System.Data.DataSetExtensions.dll" /r:"Microsoft.CSharp.dll" /r:"Syste
m.Data.dll" /r:"System.Net.Http.dll" /r:"System.Xml.dll" /r:"/usr/lib/keepass/Ke
ePass.exe" /r:"/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/
Newtonsoft.Json.dll" /r:"/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH
7zcIs5G7h/keepass2-developerextensions.dll" /resource:"/run/user/1000/KeePass/FE
21AEB3E87F2743B60418E1A02B1B13/HaveIBeenPwned.UI.BreachedEntriesDialog.resources
" /resource:"/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/HaveIBeenPw
ned.UI.CheckerPrompt.resources" /resource:"/run/user/1000/KeePass/FE21AEB3E87F27
43B60418E1A02B1B13/HaveIBeenPwned.Resources.resources"  -- "/run/user/1000/KeePa
ss/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/BaseChecker.cs" "/run/user/10
00/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedPasswor
d/HaveIBeenPwnedPasswordChecker.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B604
18E1A02B1B13/BreachCheckers/HaveIBeenPwnedPassword/HaveIBeenPwnedPasswordEntry.c
s" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveI
BeenPwnedUsername/HaveIBeenPwnedUsernameChecker.cs" "/run/user/1000/KeePass/FE21
AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedUsername/HaveIBeenPwne
dUsernameEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/Disp
layAttribute.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/UI/Bre
achedEntriesDialog.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/
UI/BreachedEntriesDialog.Designer.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B6
0418E1A02B1B13/BreachCheckers/BreachedEntry.cs" "/run/user/1000/KeePass/FE21AEB3
E87F2743B60418E1A02B1B13/BreachEnum.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743
B60418E1A02B1B13/UI/CheckerPrompt.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B6
0418E1A02B1B13/UI/CheckerPrompt.Designer.cs" "/run/user/1000/KeePass/FE21AEB3E87
F2743B60418E1A02B1B13/BreachCheckers/CloudbleedSite/CloudbleedSiteChecker.cs" "/
run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudbleed
Site/CloudbleedSiteEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02
B1B13/CheckerTypeAttribute.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A
02B1B13/BreachCheckers/HaveIBeenPwnedSite/HaveIBeenPwnedSiteChecker.cs" "/run/us
er/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedSi
te/HaveIBeenPwnedSiteEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A
02B1B13/CheckTypeEnum.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B
13/HaveIBeenPwnedExt.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B1
3/BreachCheckers/IBreach.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02
B1B13/ProgressHelper.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B1
3/ProgressItem.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/Prop
erties/AssemblyInfo.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13
/Resources.Designer.cs"
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedPassword/HaveIBeenPwnedPasswordChecker.cs(37,103): error CS0012: The type `
KeePassLib.PwEntry' is defined in an assembly that is not referenced. Consider a
dding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, P
ublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedPassword/HaveIBeenPwnedPasswordChecker.cs(37,103): error CS0012: The type `
KeePass.Plugins.IPluginHost' is defined in an assembly that is not referenced. C
onsider adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=n
eutral, PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedUsername/HaveIBeenPwnedUsernameChecker.cs(36,103): error CS0012: The type `
KeePassLib.PwEntry' is defined in an assembly that is not referenced. Consider a
dding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, P
ublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedUsername/HaveIBeenPwnedUsernameChecker.cs(36,103): error CS0012: The type `
KeePass.Plugins.IPluginHost' is defined in an assembly that is not referenced. C
onsider adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=n
eutral, PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudblee
dSite/CloudbleedSiteChecker.cs(35,103): error CS0012: The type `KeePassLib.PwEnt
ry' is defined in an assembly that is not referenced. Consider adding a referenc
e to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKeyToken=fe
d2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudblee
dSite/CloudbleedSiteChecker.cs(35,103): error CS0012: The type `KeePass.Plugins.
IPluginHost' is defined in an assembly that is not referenced. Consider adding a
 reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKe
yToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedSite/HaveIBeenPwnedSiteChecker.cs(36,103): error CS0012: The type `KeePassL
ib.PwEntry' is defined in an assembly that is not referenced. Consider adding a 
reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKey
Token=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedSite/HaveIBeenPwnedSiteChecker.cs(36,103): error CS0012: The type `KeePass.
Plugins.IPluginHost' is defined in an assembly that is not referenced. Consider 
adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, 
PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)



==============================================================================
Compiler 'v3.5':

/usr/bin/mcs /target:library /debug- /optimize+ /out:"/run/user/1000/KeePass/FE2
1AEB3E87F2743B60418E1A02B1B13/HaveIBeenPwned.dll" /r:"System.dll" /r:"System.Cor
e.dll" /r:"System.Drawing.dll" /r:"System.Windows.Forms.dll" /r:"System.Xml.Linq
.dll" /r:"System.Data.DataSetExtensions.dll" /r:"Microsoft.CSharp.dll" /r:"Syste
m.Data.dll" /r:"System.Net.Http.dll" /r:"System.Xml.dll" /r:"/usr/lib/keepass/Ke
ePass.exe" /r:"/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/
Newtonsoft.Json.dll" /r:"/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH
7zcIs5G7h/keepass2-developerextensions.dll" /resource:"/run/user/1000/KeePass/FE
21AEB3E87F2743B60418E1A02B1B13/HaveIBeenPwned.UI.BreachedEntriesDialog.resources
" /resource:"/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/HaveIBeenPw
ned.UI.CheckerPrompt.resources" /resource:"/run/user/1000/KeePass/FE21AEB3E87F27
43B60418E1A02B1B13/HaveIBeenPwned.Resources.resources"  -- "/run/user/1000/KeePa
ss/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/BaseChecker.cs" "/run/user/10
00/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedPasswor
d/HaveIBeenPwnedPasswordChecker.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B604
18E1A02B1B13/BreachCheckers/HaveIBeenPwnedPassword/HaveIBeenPwnedPasswordEntry.c
s" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveI
BeenPwnedUsername/HaveIBeenPwnedUsernameChecker.cs" "/run/user/1000/KeePass/FE21
AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedUsername/HaveIBeenPwne
dUsernameEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/Disp
layAttribute.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/UI/Bre
achedEntriesDialog.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/
UI/BreachedEntriesDialog.Designer.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B6
0418E1A02B1B13/BreachCheckers/BreachedEntry.cs" "/run/user/1000/KeePass/FE21AEB3
E87F2743B60418E1A02B1B13/BreachEnum.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743
B60418E1A02B1B13/UI/CheckerPrompt.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B6
0418E1A02B1B13/UI/CheckerPrompt.Designer.cs" "/run/user/1000/KeePass/FE21AEB3E87
F2743B60418E1A02B1B13/BreachCheckers/CloudbleedSite/CloudbleedSiteChecker.cs" "/
run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudbleed
Site/CloudbleedSiteEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02
B1B13/CheckerTypeAttribute.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A
02B1B13/BreachCheckers/HaveIBeenPwnedSite/HaveIBeenPwnedSiteChecker.cs" "/run/us
er/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeenPwnedSi
te/HaveIBeenPwnedSiteEntry.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A
02B1B13/CheckTypeEnum.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B
13/HaveIBeenPwnedExt.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B1
3/BreachCheckers/IBreach.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02
B1B13/ProgressHelper.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B1
3/ProgressItem.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/Prop
erties/AssemblyInfo.cs" "/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13
/Resources.Designer.cs"
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedPassword/HaveIBeenPwnedPasswordChecker.cs(37,103): error CS0012: The type `
KeePassLib.PwEntry' is defined in an assembly that is not referenced. Consider a
dding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, P
ublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedPassword/HaveIBeenPwnedPasswordChecker.cs(37,103): error CS0012: The type `
KeePass.Plugins.IPluginHost' is defined in an assembly that is not referenced. C
onsider adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=n
eutral, PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedUsername/HaveIBeenPwnedUsernameChecker.cs(36,103): error CS0012: The type `
KeePassLib.PwEntry' is defined in an assembly that is not referenced. Consider a
dding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, P
ublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedUsername/HaveIBeenPwnedUsernameChecker.cs(36,103): error CS0012: The type `
KeePass.Plugins.IPluginHost' is defined in an assembly that is not referenced. C
onsider adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=n
eutral, PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudblee
dSite/CloudbleedSiteChecker.cs(35,103): error CS0012: The type `KeePassLib.PwEnt
ry' is defined in an assembly that is not referenced. Consider adding a referenc
e to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKeyToken=fe
d2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/Cloudblee
dSite/CloudbleedSiteChecker.cs(35,103): error CS0012: The type `KeePass.Plugins.
IPluginHost' is defined in an assembly that is not referenced. Consider adding a
 reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKe
yToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedSite/HaveIBeenPwnedSiteChecker.cs(36,103): error CS0012: The type `KeePassL
ib.PwEntry' is defined in an assembly that is not referenced. Consider adding a 
reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, PublicKey
Token=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
/run/user/1000/KeePass/FE21AEB3E87F2743B60418E1A02B1B13/BreachCheckers/HaveIBeen
PwnedSite/HaveIBeenPwnedSiteChecker.cs(36,103): error CS0012: The type `KeePass.
Plugins.IPluginHost' is defined in an assembly that is not referenced. Consider 
adding a reference to assembly `KeePass, Version=2.36.0.17315, Culture=neutral, 
PublicKeyToken=fed2ed7716aecf5c'
/home/user/.local/share/KeePass/PluginCache/Q9L0nMVXpsH7zcIs5G7h/keepass2-develo
perextensions.dll (Location of the symbol related to previous error)
```

**Comment by boistordu** [comment]
Since ti says keepass 2.36  which version of your mod would be compatible with 2.34?

**Comment by andrew-schofield** [comment]
Hmm, looks like I've messed up the plgx file so it includes a precompiled DLL which references 2 36 (the version I was using when that plgx was created).

I'll try and work out how to fix it, but in the meantime I'd strongly recommend using the latest version of KeePass (2.34 was released in 2016).

**Comment by boistordu** [comment]
yeah of course, it s just like I said the fedora repo only contains 2.34 ....

**Comment by andrew-schofield** [comment]
This should now be fixed in v1.2.2. There is no longer be a dll included that depends on KeePass 2.36.

**Comment by shad0whawk** [comment]
I tried downloading the latest plgx from the link provided but it still shows as 1.2.1 within Keepass.  Is there another way to get the version 1.2.2?

**Comment by andrew-schofield** [comment]
Sorry about that, it turns out I didn't push the correct plgx file after rebuilding. The correct version should be available now.
